services:
  jupyter:
    build: .
    container_name: docker-notebooks-example
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
    command: start-notebook.sh --NotebookApp.notebook_dir=/home/jovyan/work --NotebookApp.token=''
    restart: always
